### Imports and Installations

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Analyze output of actuated simulation 
Timesteps 25200 - 29700

In [22]:
df = pd.read_csv('../src/data/actuated_output/actuated_output_9000steps.csv')
df

,Step,num_vehicles,vehicle_types,avg_speed,localCO2Emission,localCOEmission,localHCEmission,localPMxEmission,localNOxEmission,localNoiseEmission,...,localStoppedVehicles,totalCO2Emission,totalCOEmission,totalHCEmission,totalPMxEmission,totalNOxEmission,totalFuelConsumption,totalNoiseEmission,totalWaitingTime,totalStoppedVehicles
0,25200,0,[],0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,1.123389e+04,359.172222,1.453889,2.442333,86.401389,3.550833e+03,178.991223,0.0,4
1,25201,0,[],0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,2.186324e+04,666.801335,3.018414,2.957748,97.425541,6.936337e+03,271.159876,0.0,1
2,25202,0,[],0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,3.250170e+04,924.722737,4.318140,3.586446,120.598029,1.031744e+04,335.695376,0.0,1
3,25203,0,[],0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,5.051227e+04,1100.544598,5.200979,6.431233,241.016657,1.601038e+04,463.885510,1.0,3
4,25204,0,[],0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,5.765308e+04,1096.456427,5.319689,6.791613,271.803409,1.827040e+04,538.493184,0.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8995,34195,38,"['DEFAULT_VEHTYPE', 'DEFAULT_VEHTYPE', 'tram',...",0.226243,110431.666667,4380.391667,25.960556,14.765833,516.510000,655.847704,...,37,5.788134e+06,137722.796548,719.416874,851.741298,34027.275633,1.832296e+06,82597.281980,62801.0,1091
8996,34196,38,"['DEFAULT_VEHTYPE', 'DEFAULT_VEHTYPE', 'tram',...",0.147296,110431.666667,4380.391667,25.960556,14.765833,516.510000,655.847704,...,37,5.727602e+06,138064.364180,708.921066,845.966421,33559.874492,1.813223e+06,82569.476849,63212.0,1081
8997,34197,38,"['DEFAULT_VEHTYPE', 'DEFAULT_VEHTYPE', 'tram',...",0.068349,110431.666667,4380.391667,25.960556,14.765833,516.510000,655.847704,...,37,5.544982e+06,137742.597187,708.037996,829.195985,32486.840101,1.755576e+06,82407.226339,63880.0,1089
8998,34198,38,"['DEFAULT_VEHTYPE', 'DEFAULT_VEHTYPE', 'tram',...",0.000000,110431.666667,4380.391667,25.960556,14.765833,516.510000,655.847704,...,38,5.706132e+06,139277.289512,711.131175,842.634931,33225.130413,1.806594e+06,82559.416131,64726.0,1095
8999,34199,39,"['DEFAULT_VEHTYPE', 'DEFAULT_VEHTYPE', 'tram',...",0.000000,113056.388889,4545.169444,26.772500,14.831806,517.714444,656.081340,...,39,5.683498e+06,140200.870707,725.659631,837.645970,32884.116890,1.799588e+06,82502.491470,64957.0,1099

In [23]:
df.localCO2Emission.describe()

count      9000.000000
mean     145793.222366
std       76960.470427
min           0.000000
25%       83189.443767
50%      128871.308383
75%      209140.956129
max      382082.445051
Name: localCO2Emission, dtype: float64

In [3]:
df_ppo = pd.read_csv('../src/data/evaluation/avg_speed_200_1800.csv')
df_ppo

,step,CO2_emissions,CO_emissions,HC_emissions,PMx_emissions,NOx_emissions,waiting_time,total_num_stops,current_reward
0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0,1.000000
1,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0,1.000000
2,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0,1.000000
3,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0,1.000000
4,4,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0,1.000000
...,...,...,...,...,...,...,...,...,...
1795,1795,132019.729654,4253.271847,20.284393,21.527913,794.097379,1297.0,0,0.045125
1796,1796,132032.731019,4254.697594,20.291255,21.528618,794.104923,1335.0,0,0.042362
1797,1797,132039.266604,4255.676395,20.295911,21.529050,794.108553,1373.0,0,0.016531
1798,1798,132041.891882,4256.065829,20.297763,21.529226,794.110319,1411.0,0,0.056728
1799,1799,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0,0.104237

In [4]:
df_ppo.CO2_emissions.describe()

count      1800.000000
mean      79731.322665
std       37847.394858
min           0.000000
25%       58686.117924
50%       82708.463934
75%      106940.187146
max      200804.083972
Name: CO2_emissions, dtype: float64